### ISSUE TITLE
Support for one-factor / first step

### ISSUE THREAD

**Issue by beat2** [wso2-extensions/identity-outbound-auth-x509#3]
Currently the authenticator is two-factor only (needs first step) [1]. This makes sense where a certificate is imported to the browser and not secured with a password.

In our case the certificates are stored on hardware tokens which need a password / PIN to open (pkcs11 / windows-certstore). As such, we would like to have this x509 authentication as the first and only step to login.
This usecase could be useful for a number of "eID" [2] hardware tokens, like the Belgium eID or the Swiss SuisseID.

[1] http://mail.wso2.org/mailarchive/architecture/2016-April/023633.html
[2] https://en.wikipedia.org/wiki/Electronic_identification

**Comment by hmrajas** [comment]
we can consider this in our road map.

**Comment by andypower** [comment]
Hi all,
after the latest commits I tried to configure the "one step" x509 certificate using a custom application but I am unable to make it working. 
The Identity Server error log shows that message: "X509Certificate not found" 
[MesaggiErrore.txt](https://github.com/wso2-extensions/identity-outbound-auth-x509/files/445298/MesaggiErrore.txt)
I am trying to find a solution but I can't realize how to overcome this obstacle.

Googling I found that the problem may be related to an erroneous server/client certificate configuration and I tryied to follow the [setup.txt](https://github.com/wso2-extensions/identity-outbound-auth-x509/blob/master/component/setup.txt) instructions running the [create_certificates.sh](https://github.com/wso2-extensions/identity-outbound-auth-x509/blob/master/component/src/certificate/create_certificates.sh) script.
I imported the certificate inside the Chrome certificate repository and when I try to access to my custom application the browser prompt a window asking for the certificate to use. After confirming the use of the generate certificate the Identity Server shows the following message: 
"SAML 2.0 based Single Sign-On
Error when processing the authentication request!
Please try login again."

Please, help me to figure out a solution or, if you want, give some some tips for the debug.

This is my Connector configuration:
`<Connector protocol="org.apache.coyote.http11.Http11NioProtocol"
            port="8443" maxThreads="200" scheme="https" secure="true"
            SSLEnabled="true" 
            keystoreFile="d:\foobar.jks" keystorePass="foobarpwd"
            truststoreFile="d:\cacerts.jks" truststorePass="cacertspassword"
            clientAuth="want" sslProtocol="TLS"
        />`
I used the generated cacerts.jks as truststore and the foobar.jks as keystore. Is it right?

Thanks in advance.

**Comment by hmrajas** [comment]
Change the order of the connector in catalina-server.xml and try again.
